### PR TITLE
Critical bug fix

### PR DESCRIPTION
**Pull request by Random-629671**
I am sorry everyone if you had a ban due captcha checking not work due to my work

### CODE REVIEW

**Comment by Random-629671** [comment]
Somehow on first test pharse captcha checking still work so i commit it anyway

**Comment by Random-629671** [comment]
Mid0 plz next time read my code at least why u merge so fast ;-;

**Comment by EchoQuill** [comment]
> I am sorry everyone if you had a ban due captcha checking not work due to my work

everyone makes mistakes, make sure to test well next time when changing imp parts like captcha detection etc.

**Comment by Mid0aria** [comment]
Tell me which issues you fixed and I'll close it.

**Comment by Random-629671** [comment]
Summary: if there was captcha message, hunt/battle check will have chance to not detect the hunt/battle message, it will recheck and force rehunt/battle (the else statement), but if it happen, i didn't make it to recheck the captcha
Very critical because there is a chance to someone get banned

**Comment by Random-629671** [comment]
Seriously sorry for my bad

**Comment by Random-629671** [comment]
wait mid0 can u
umm...
remove two "!" in the battlecheck function before global.mainhuntpaused?
i was so nervous because of the bug

**Comment by Random-629671** [comment]
Mid0 can u remove the "!" in the battlecheck and extrabattlecheck function before global.mainhuntpaused in what i added plz i was so nervous bc the bug @Mid0aria

**Pull request merged**
