### PR TITLE
hjunt and battle with random interval

### PR DESCRIPTION
**Pull request by hawi-glitch**
added random interval between hunt and battle

### CODE REVIEW

**Comment by VihaanReddyM** [comment]
how is it usefull???

**Comment by VihaanReddyM** [comment]
After checking, i realised that it will interrupt with the get requests made by the bot, so it may lead to some functions failing

**Comment by hawi-glitch** [comment]
With specific intervals, the bot will detect it, sending captcha frequently

**Comment by VihaanReddyM** [comment]
it will be hard to do that and the bot works fine only now

**Pull request closed without merging**
