### PR TITLE
Touching ban bypass system and notify system

### PR DESCRIPTION
**Pull request by Random-629671**
Since i got banned, i do not want other got banned too ;-;

What did i do?

Simply make the system check from 1 latest message up to 3 or 5, so that the chance of miss the captcha message will nealy zero.
I also make a user-control number of notify times to make sure no one miss the captcha and happy.

Waiting for unban ;-;

### CODE REVIEW

**Comment by Random-629671** [comment]
damn i missclicked n for b
i am so stupid ;-;

**Comment by Random-629671** [comment]
but don't worry it only the text when get the number so plase go easy on me

**Comment by Random-629671** [comment]
... i missclicked again

**Comment by Random-629671** [comment]
i wont be suprise if i noice i forgot something tomorrow...

**Comment by mallusrgreatv2** [comment]
what good does notifynumber do? annoy the user trying to close 10 notifications?

**Comment by Random-629671** [comment]
since that is user choice and default is 1, it quite not have any diff, but if someone is run the bot under their work, they might need a bigger number of notify time to noice

**Pull request merged**
