### PR TITLE
(FInal) Fix some questing problem and improve some embeds message content reader

### PR DESCRIPTION
**Pull request by Random-629671**
Final update for function. Still maintain if found a bug.

What did i do:
Change `getquests` inside the small quest doing function to make it get quest correctly
Remove a unused variable in `questuseactioncommand` that make bot unable to get quest
Make a new embeds content reader that will check the content more accurate (only apply to `getquests` and `checklist` function)
Make a interval for `checklist` so it will update without the need of restart bot
Make socket show a completed/locked quest message when bot cannot found any active quest or after complete a quest
Remove some `\\` that mostly added by a bot in `getquests` function. In that place i used it to check the `\``...

After all, thank you, mid0, and also this project to help me improve my coding skill. Or at least, js coding skill.

### CODE REVIEW

**Comment by Mid0aria** [comment]
https://github.com/Mid0aria/owofarmbot_stable
can you contribute to this project?

**Comment by Random-629671** [comment]
isn't that project close source?
also how to update this new version?

**Comment by Random-629671** [comment]
more also what is mid0 service auth key use for?

**Comment by mallusrgreatv2** [comment]
> isn't that project close source? also how to update this new version?

He posted the unobfuscated code recently for us to create PRs, since he's going to be away and can't contribute

**Comment by Random-629671** [comment]
@Mid0aria you didn't call the `checkUpdate` function inside bot.js
if user using v1.0.8.4 they will know there are new ver but if they are using v1.0.8.5 they will never know

**Comment by Random-629671** [comment]
when i mean never it actually never unless they go to this github page
even though v1.0.8.5 only have a little questing bug but... yea, they will stuck in v1.0.8.5 forever

**Pull request merged**
