### PR TITLE
Better coinflip and slot

### PR DESCRIPTION
**Pull request by VihaanReddyM**
In Issue #69, [peng1285](https://github.com/peng1285) provided an insightful idea, which I have incorporated into the coin flip feature. However, instead of doubling the wager after each loss, I have opted to triple it. I'm pleased to announce that the same functionality will be extended to the slot feature, as per his request.

- [x] Add this feature for coinflip
- [x] Add multiplier that can be changable
- [x] Update ReadMe file
- [x] Ban proof in the gambling channel
- [x] Update the version of the bot

### CODE REVIEW

**Comment by VihaanReddyM** [comment]
I think everything is done

**Comment by VihaanReddyM** [comment]
@Mid0aria pls check the PR and pull it in

**Comment by Mid0aria** [comment]
change version in bot.js 
image

(1.0.4)

**Comment by Mid0aria** [comment]
and add this future in readme.md

**Comment by VihaanReddyM** [comment]
the feature is already there in read me so i do not really know what to change

**Comment by VihaanReddyM** [comment]
hey i am not really good at Readme and i am unable to do it can you do it for me here is a sample picture

image

**Comment by peng1285** [comment]
@VihaanReddyM @Mid0aria  can i get you contact?

**Comment by peng1285** [comment]
@VihaanReddyM @Mid0aria i want you to make one selfbot for me if you can i will pay you

**Comment by VihaanReddyM** [comment]
yea i can do that .... but one small issue because  have my exams i am being active right now..... i will be active again from 14th March because that is my last exam date. is that ok with you

**Comment by peng1285** [comment]
@VihaanReddyM give me your discord username or you can add me peng_ch

**Comment by VihaanReddyM** [comment]
i added you

**Comment by Mid0aria** [comment]
> @VihaanReddyM give me your discord username or you can add me peng_ch

telegram: https://midohazretleri.t.me

**Pull request merged**
