### PR TITLE
Mutiple changes (mainly aim to avoid new OwO captcha system)

### PR DESCRIPTION
**Pull request by Random-629671**
After a week of testing, most case i got a captcha every 5 minutes (actually). So i decied to check what is the problem.

One more week of testing, i think OwO will send captcha if use trigger the "...slow down and use the command after..." too much.
I can barely sure its actually the problem because when i do some changes, now I can run the bot for ONE hour straight.

What did i do:
Modify hunt and battle
Modify inventory check
Make sure the bot will always check the quest at boot
Remove some unused code block

Other notes: 
The check quest is getting wrong quest progress, but i am not able to understand its logic and it is not too important.
Need to check extra token because i don't have one.

Now i know why it required two thread for each token type...
And also i need to test everythings more carefully from now on (or get a tester :< )

### CODE REVIEW

**Comment by Mid0aria** [comment]
set version v1.0.7.2

**Comment by Random-629671** [comment]
Done

**Comment by Random-629671** [comment]
Just did a little change to make bot get quest and chacklist more accurate if auto quest channel is the same as main channel

**Comment by Random-629671** [comment]
Still don't know why my "tab" is longer than github "tab" :\

**Comment by Mid0aria** [comment]
> Still don't know why my "tab" is longer than github "tab" :\

use prettier and set ur visual studio code tab spaces is 4

**Pull request merged**
