### PR TITLE
Fix some `console.error` things, earlier pray/curse with a fix and update version

### PR DESCRIPTION
**Pull request by Random-629671**
U forgot it

### CODE REVIEW

**Comment by Random-629671** [comment]
or change into 1.0.8.2 to make sure everyone get it

**Comment by Random-629671** [comment]
oh no...
don't update it revert

**Comment by Random-629671** [comment]
```
 if (
                                    bod[i].embeds[0].author.name.includes(
                                        "Quest Log"
                                    )
                                )
                                    cont = bod[i].embeds;
                            } catch (error) {
                                console.error(error);
```

in this part it will check though all embed found, so it will highly have an error, that's why i do not show the error on console, plz remove it
at first i think i messed something up :|
i will commit directly here wait

**Comment by Random-629671** [comment]
wait you add console.error(error) every try catch???

**Comment by Random-629671** [comment]
ok hear me out

Fixed pray/curse delay on first run by make it run after 16 secs (instead of `timecurseinterval` (305 secs) in previous version)
Remove some expected `console.error`
Update version

Did you use a bot to update another bot?

**Comment by Random-629671** [comment]
Oh i see the curse "real" problem wait

**Comment by Random-629671** [comment]
I wonder why my extra account got banned
And it because the promt didn't showing
The reason is you added more "\" in the `createpromt` function

**Comment by Random-629671** [comment]
died again
cannot check any function run on 2 account :D

**Comment by Mid0aria** [comment]
use eslint :)

**Comment by Mid0aria** [comment]
https://eslint.org/

**Comment by Random-629671** [comment]
thank to the bot :)

**Pull request merged**
